SELECT ga.DESCRIPCION_AGENCIA, SUM(ca.DEBITO), SUM(ca.CREDITO) FROM "con$auxiliar" ca
INNER JOIN "gen$agencia" ga ON ga.ID_AGENCIA = ca.ID_AGENCIA
WHERE ca.CODIGO = '311520010000000000' AND ca.ESTADOAUX  = 'C' 
GROUP BY 1