SELECT 
 gp.ID_PERSONA, 
 gp.NOMBRE, 
 gp.PRIMER_APELLIDO, 
 gp.SEGUNDO_APELLIDO, 
 gd.MUNICIPIO, 
 gd.BARRIO, 
 ci.DESCRIPCION_INVERSION,
 cs.FECHA_RECEPCION,
 cc.FECHA_DESEMBOLSO,
 cs.VALOR_SOLICITADO,
 cc.VALOR_DESEMBOLSO,
 cc.PLAZO_COLOCACION,
 ge.NOMBRE || ' ' || ge.PRIMER_APELLIDO || ' ' || ge.SEGUNDO_APELLIDO AS ASESOR,
 cc.ID_COLOCACION,
 gpa.ID_ESTRATO
 FROM 
"col$colocacion" cc
INNER JOIN "col$desembolso" cd ON cd.ID_COLOCACION = cc.ID_COLOCACION 
INNER JOIN "col$solicitud" cs ON cs.ID_SOLICITUD = cd.ID_SOLICITUD 
INNER JOIN COLOCACIONASESOR ca ON ca.ID_COLOCACION = cc.ID_COLOCACION 
INNER JOIN ASESOR a ON a.ASES_ID = ca.ASES_ID
INNER JOIN "gen$empleado" ge ON ge.ID_EMPLEADO = a.ID_EMPLEADO
INNER JOIN "gen$persona" gp ON gp.ID_IDENTIFICACION = cc.ID_IDENTIFICACION AND gp.ID_PERSONA = cc.ID_PERSONA
INNER JOIN "gen$persadicional" gpa ON gpa.ID_IDENTIFICACION = gp.ID_IDENTIFICACION AND gpa.ID_PERSONA = gp.ID_PERSONA 
INNER JOIN "gen$direccion" gd ON gd.ID_IDENTIFICACION = gp.ID_IDENTIFICACION AND gd.ID_PERSONA = cc.ID_PERSONA AND gd.ID_DIRECCION = 1
INNER JOIN "col$inversion" ci ON ci.ID_INVERSION = cc.ID_INVERSION
WHERE cc.FECHA_DESEMBOLSO BETWEEN '2022-01-01' AND '2022-07-31' AND cc.ID_ESTADO_COLOCACION IN (0,1,2,6,7)
