SELECT cc.ID_CLASIFICACION, 
	cc.ID_ARRASTRE,
	cp.COD_PROV_CAPITAL,
	(SELECT SALDO FROM VALOR_AGENCIA(2,cp.COD_PROV_CAPITAL)) AS SALDO_PUC,
    SUM(DEUDA) AS DEUDA,
    SUM(PCAPITAL) AS K_PROV,
    SUM(PINTERES) AS I_PROV,
	SUM(PCAPITAL_REC) AS K_REC, 
	SUM(PINTERES_REC) AS I_REC,
	SUM(PCAPITAL_REV) AS K_REV,
	SUM(PINTERES_REV) AS I_REV,
	SUM(PCAPITAL_GAS) AS K_GAS,
	SUM(PINTERES_GAS) AS I_GAS
FROM
"col$causaciondiaria" cc 
LEFT JOIN "col$codigospuc" cp ON cp.ID_CLASIFICACION = cc.ID_CLASIFICACION AND cp.ID_CATEGORIA = cc.ID_ARRASTRE AND cp.ID_GARANTIA = 2
WHERE cc.FECHA_CORTE = '2022-02-28'
GROUP BY 1,2,3