SELECT DISTINCT p.ID_PERSONA,
 p.NOMBRE || ' ' || p.PRIMER_APELLIDO || ' ' || p.SEGUNDO_APELLIDO AS NOMBRE,
 p.EMAIL, d.TELEFONO1 || ' ' || d.TELEFONO2 AS TELEFONO, p.PROFESION
FROM "gen$persona" p
LEFT JOIN "gen$direccion" d ON d.ID_IDENTIFICACION = p.ID_IDENTIFICACION and d.ID_PERSONA = p.ID_PERSONA and d.CONSECUTIVO = 1
LEFT JOIN "gen$persadicional" a ON a.ID_IDENTIFICACION = p.ID_IDENTIFICACION and a.ID_PERSONA = p.ID_PERSONA
WHERE p.PROFESION LIKE '%INDEPEND%' AND ((d.TELEFONO1 <> '' OR d.TELEFONO2 <>'') OR p.EMAIL <> '')
AND (SELECT COUNT(*) FROM "col$colocacion" WHERE ID_IDENTIFICACION = p.ID_IDENTIFICACION and ID_PERSONA = p.ID_PERSONA) > 0