SELECT 
    ID_CLASIFICACION,
	SUM(PCAPITAL_REC) AS KREC, 
	SUM(PINTERES_REC) AS IREC, 
	SUM(PCAPITAL_REV) AS KREV, 
	SUM(PINTERES_REV) AS IREV,
	SUM(PCAPITAL_GAS) AS KGAS,
	SUM(PINTERES_GAS) AS IGAS 
FROM "col$causaciondiaria" cc 
WHERE cc.FECHA_CORTE = '2021-11-30'
GROUP BY 1