SELECT 
	IIF(POSITION('-' IN cc.ID_PERSONA) = 0, cc.ID_PERSONA, (SUBSTRING(cc.ID_PERSONA FROM 1 FOR (POSITION('-' IN cc.ID_PERSONA)-1)))) AS IDENTIFICACION, 
	TRIM(IIF(POSITION(' ' IN gp.NOMBRE) = 0,gp.NOMBRE,(SUBSTRING(gp.NOMBRE FROM 1 FOR (POSITION(' ' IN gp.NOMBRE))))) || ' ' || gp.PRIMER_APELLIDO) AS NOMBRE,
	LPAD(IIF(POSITION('-' IN cc.ID_PERSONA) = 0, cc.ID_PERSONA, (SUBSTRING(cc.ID_PERSONA FROM 1 FOR (POSITION('-' IN cc.ID_PERSONA)-1)))), 13, '0') AS REFERENCIA1, 
	DATEADD(360 DAY TO CURRENT_DATE) AS FECHA_VENCIMIENTO
	FROM "col$colocacion"  cc
INNER JOIN "gen$persona" gp ON gp.ID_IDENTIFICACION = cc.ID_IDENTIFICACION AND gp.ID_PERSONA = cc.ID_PERSONA 
WHERE cc.ID_ESTADO_COLOCACION IN (0,1,2)