SELECT p.ID_PERSONA, p.PRIMER_APELLIDO, p.SEGUNDO_APELLIDO, p.NOMBRE, d.DIRECCION, d.COD_MUNICIPIO, d.MUNICIPIO
FROM "gen$persona" p
LEFT JOIN "gen$direccion" d ON d.ID_IDENTIFICACION = p.ID_IDENTIFICACION  AND d.ID_PERSONA = p.ID_PERSONA AND d.CONSECUTIVO = 1
WHERE p.ID_IDENTIFICACION > 2