SELECT 
	gp.ID_PERSONA AS DOCUMENTO_IDENTIDAD,
	gp.FECHA_NACIMIENTO AS FECHA_NACIMIENTO,
	gp.SEXO AS GENERO,
	gd.BARRIO,
	gd.MUNICIPIO
FROM "col$causaciondiaria" cd 
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = cd.ID_COLOCACION 
INNER JOIN "gen$persona" gp ON gp.ID_IDENTIFICACION = cc.ID_IDENTIFICACION AND gp.ID_PERSONA = cc.ID_PERSONA
INNER JOIN "gen$direccion" gd ON gd.ID_IDENTIFICACION = cc.ID_IDENTIFACION AND gd.ID_PERSONA = cc.ID_PERSONA AND gd.ID_DIRECCION = 1
WHERE cc.ID_ESTADO_COLOCACION IN (0,1,2) AND cd.FECHA_CORTE= '2021-12-30'
ORDER BY 1;

SELECT 
 cc.ID_COLOCACION AS NUMERO_CREDITO,
 cl.DESCRIPCION_LINEA AS LINEA_CREDITO,
 cc.FECHA_DESEMBOLSO AS FECHA_DESEMBOLSO,
 cc.TASA_INTERES_CORRIENTE AS TASA_INTERES,
 cc.PLAZO_COLOCACION / 30 AS PLAZO_CREDITO,
 cc.AMORTIZA_INTERES / 30 AS  PERIODICIDAD_PAGO,
 CASE ct.INTERES 
   WHEN 'A' THEN 1
   WHEN 'V' THEN 0
 END AS FORMA_PAGO,
 cc.VALOR_DESEMBOLSO  AS MONTO_DESEMBOLSO,
 (cc.VALOR_DESEMBOLSO - cc.ABONOS_CAPITAL) AS SALDO_ACTUAL,
 (SELECT COUNT(*) FROM "col$tablaliquidacion" ct WHERE ct.ID_COLOCACION = cc.ID_COLOCACION AND ct.PAGADA = 1) AS CUOTAS_PAGADAS,
 ce.DESCRIPCION_ESTADO_COLOCACION  AS ESTADO_ACTUAL,
 cc.ID_PERSONA
FROM "col$causaciondiaria" cd
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = cd.ID_COLOCACION 
INNER JOIN "col$lineas" cl ON cl.ID_LINEA = cc.ID_LINEA
INNER JOIN "col$tiposcuota" ct ON ct.ID_TIPOS_CUOTA = cc.ID_TIPO_CUOTA
INNER JOIN "col$estado" ce ON ce.ID_ESTADO_COLOCACION = cc.ID_ESTADO_COLOCACION 
WHERE cc.ID_ESTADO_COLOCACION IN (0,1,2)

SELECT * FROM (
SELECT 
 	ce.ID_COLOCACION AS NUMERO_CREDITO,
	ce.CUOTA_EXTRACTO AS NUMERO_CUOTA,
    ce.FECHA_EXTRACTO AS FECHA_PAGO_CUOTA,
	1 AS CONSECUTIVO,
	'ABONO CAPITAL' AS CONCEPTO_PAGO,
	ce.ABONO_CAPITAL  AS VALOR_CONCEPTO,
	EXTRACT(DAY FROM DATEADD(cc.DIAS_PAGO DAY TO cc.FECHA_DESEMBOLSO)) AS DIAS_PAGO,
	f.FACT_NUMERO
FROM "col$causaciondiaria" cd
INNER JOIN "col$extracto" ce ON ce.ID_COLOCACION = cd.ID_COLOCACION  
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = ce.ID_COLOCACION 
LEFT JOIN FACTURA f ON f.ID_COMPROBANTE = ce.ID_CBTE_COLOCACION AND EXTRACT(YEAR FROM f.FACT_FECHA) = EXTRACT(YEAR FROM ce.FECHA_EXTRACTO) 
WHERE cd.FECHA_CORTE = '2021-12-30' AND cd.ID_ESTADO IN (0,1,2)
UNION
SELECT 
 	ce.ID_COLOCACION AS NUMERO_CREDITO,
	ce.CUOTA_EXTRACTO AS NUMERO_CUOTA,
    ce.FECHA_EXTRACTO AS FECHA_PAGO_CUOTA,
	2 AS CONSECUTIVO,
	'ABONO INTERES ANTICIPADO' AS CONCEPTO_PAGO,
	ce.ABONO_ANTICIPADO AS VALOR_CONCEPTO,
	EXTRACT(DAY FROM DATEADD(cc.DIAS_PAGO DAY TO cc.FECHA_DESEMBOLSO)) AS DIAS_PAGO,
	f.FACT_NUMERO
FROM "col$causaciondiaria" cd
INNER JOIN "col$extracto" ce ON ce.ID_COLOCACION = cd.ID_COLOCACION  
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = ce.ID_COLOCACION 
LEFT JOIN FACTURA f ON f.ID_COMPROBANTE = ce.ID_CBTE_COLOCACION AND EXTRACT(YEAR FROM f.FACT_FECHA) = EXTRACT(YEAR FROM ce.FECHA_EXTRACTO) 
WHERE cd.FECHA_CORTE = '2021-12-30' AND cd.ID_ESTADO IN (0,1,2)
UNION 
SELECT 
 	ce.ID_COLOCACION AS NUMERO_CREDITO,
	ce.CUOTA_EXTRACTO AS NUMERO_CUOTA,
    ce.FECHA_EXTRACTO AS FECHA_PAGO_CUOTA,
	3 AS CONSECUTIVO,
	'ABONO INTERES CAUSADO' AS CONCEPTO_PAGO,
	ce.ABONO_CXC AS VALOR_CONCEPTO,
	EXTRACT(DAY FROM DATEADD(cc.DIAS_PAGO DAY TO cc.FECHA_DESEMBOLSO)) AS DIAS_PAGO,
	f.FACT_NUMERO
FROM "col$causaciondiaria" cd
INNER JOIN "col$extracto" ce ON ce.ID_COLOCACION = cd.ID_COLOCACION  
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = ce.ID_COLOCACION 
LEFT JOIN FACTURA f ON f.ID_COMPROBANTE = ce.ID_CBTE_COLOCACION AND EXTRACT(YEAR FROM f.FACT_FECHA) = EXTRACT(YEAR FROM ce.FECHA_EXTRACTO) 
WHERE cd.FECHA_CORTE = '2021-12-30' AND cd.ID_ESTADO IN (0,1,2)
UNION
SELECT 
 	ce.ID_COLOCACION AS NUMERO_CREDITO,
	ce.CUOTA_EXTRACTO AS NUMERO_CUOTA,
    ce.FECHA_EXTRACTO AS FECHA_PAGO_CUOTA,
	4 AS CONSECUTIVO,
	'ABONO INTERES POR SERVICIO' AS CONCEPTO_PAGO,
	(ce.ABONO_CAPITAL + ce.ABONO_CXC + ce.ABONO_ANTICIPADO + ce.ABONO_SERVICIOS  + ce.ABONO_MORA + ce.ABONO_PAGXCLI + ce.ABONO_HONORARIOS  + ce.ABONO_OTROS) AS VALOR_CONCEPTO,
	EXTRACT(DAY FROM DATEADD(cc.DIAS_PAGO DAY TO cc.FECHA_DESEMBOLSO)) AS DIAS_PAGO,
	f.FACT_NUMERO
FROM "col$causaciondiaria" cd
INNER JOIN "col$extracto" ce ON ce.ID_COLOCACION = cd.ID_COLOCACION  
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = ce.ID_COLOCACION 
LEFT JOIN FACTURA f ON f.ID_COMPROBANTE = ce.ID_CBTE_COLOCACION AND EXTRACT(YEAR FROM f.FACT_FECHA) = EXTRACT(YEAR FROM ce.FECHA_EXTRACTO) 
WHERE cd.FECHA_CORTE = '2021-12-30' AND cd.ID_ESTADO IN (0,1,2)
UNION
SELECT 
 	ce.ID_COLOCACION AS NUMERO_CREDITO,
	ce.CUOTA_EXTRACTO AS NUMERO_CUOTA,
    ce.FECHA_EXTRACTO AS FECHA_PAGO_CUOTA,
	5 AS CONSECUTIVO,
	'ABONO INTERES POR MORA' AS CONCEPTO_PAGO,
	ce.ABONO_MORA AS VALOR_CONCEPTO,
	EXTRACT(DAY FROM DATEADD(cc.DIAS_PAGO DAY TO cc.FECHA_DESEMBOLSO)) AS DIAS_PAGO,
	f.FACT_NUMERO
FROM "col$causaciondiaria" cd
INNER JOIN "col$extracto" ce ON ce.ID_COLOCACION = cd.ID_COLOCACION  
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = ce.ID_COLOCACION 
LEFT JOIN FACTURA f ON f.ID_COMPROBANTE = ce.ID_CBTE_COLOCACION AND EXTRACT(YEAR FROM f.FACT_FECHA) = EXTRACT(YEAR FROM ce.FECHA_EXTRACTO) 
WHERE cd.FECHA_CORTE = '2021-12-30' AND cd.ID_ESTADO IN (0,1,2)
UNION
SELECT 
 	ce.ID_COLOCACION AS NUMERO_CREDITO,
	ce.CUOTA_EXTRACTO AS NUMERO_CUOTA,
    ce.FECHA_EXTRACTO AS FECHA_PAGO_CUOTA,
	6 AS CONSECUTIVO,
	'ABONO PAGO POR CUENTA DEL CLIENTE (COSTAS)' AS CONCEPTO_PAGO,
	ce.ABONO_PAGXCLI AS VALOR_CONCEPTO,
	EXTRACT(DAY FROM DATEADD(cc.DIAS_PAGO DAY TO cc.FECHA_DESEMBOLSO)) AS DIAS_PAGO,
	f.FACT_NUMERO
FROM "col$causaciondiaria" cd
INNER JOIN "col$extracto" ce ON ce.ID_COLOCACION = cd.ID_COLOCACION  
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = ce.ID_COLOCACION 
LEFT JOIN FACTURA f ON f.ID_COMPROBANTE = ce.ID_CBTE_COLOCACION AND EXTRACT(YEAR FROM f.FACT_FECHA) = EXTRACT(YEAR FROM ce.FECHA_EXTRACTO) 
WHERE cd.FECHA_CORTE = '2021-12-30' AND cd.ID_ESTADO IN (0,1,2)
UNION
SELECT 
 	ce.ID_COLOCACION AS NUMERO_CREDITO,
	ce.CUOTA_EXTRACTO AS NUMERO_CUOTA,
    ce.FECHA_EXTRACTO AS FECHA_PAGO_CUOTA,
	7 AS CONSECUTIVO,
	'ABONO POR HONORARIOS' AS CONCEPTO_PAGO,
	(ce.ABONO_CAPITAL + ce.ABONO_CXC + ce.ABONO_ANTICIPADO + ce.ABONO_SERVICIOS  + ce.ABONO_MORA + ce.ABONO_PAGXCLI + ce.ABONO_HONORARIOS  + ce.ABONO_OTROS) AS VALOR_CONCEPTO,
	EXTRACT(DAY FROM DATEADD(cc.DIAS_PAGO DAY TO cc.FECHA_DESEMBOLSO)) AS DIAS_PAGO,
	f.FACT_NUMERO
FROM "col$causaciondiaria" cd
INNER JOIN "col$extracto" ce ON ce.ID_COLOCACION = cd.ID_COLOCACION  
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = ce.ID_COLOCACION 
LEFT JOIN FACTURA f ON f.ID_COMPROBANTE = ce.ID_CBTE_COLOCACION AND EXTRACT(YEAR FROM f.FACT_FECHA) = EXTRACT(YEAR FROM ce.FECHA_EXTRACTO) 
WHERE cd.FECHA_CORTE = '2021-12-30' AND cd.ID_ESTADO IN (0,1,2)
UNION
SELECT 
 	ce.ID_COLOCACION AS NUMERO_CREDITO,
	ce.CUOTA_EXTRACTO AS NUMERO_CUOTA,
    ce.FECHA_EXTRACTO AS FECHA_PAGO_CUOTA,
	8 AS CONSECUTIVO,
	'ABONO OTROS CONCEPTOS' AS CONCEPTO_PAGO,
	ce.ABONO_OTROS AS VALOR_CONCEPTO,
	EXTRACT(DAY FROM DATEADD(cc.DIAS_PAGO DAY TO cc.FECHA_DESEMBOLSO)) AS DIAS_PAGO,
	f.FACT_NUMERO
FROM "col$causaciondiaria" cd
INNER JOIN "col$extracto" ce ON ce.ID_COLOCACION = cd.ID_COLOCACION  
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = ce.ID_COLOCACION 
LEFT JOIN FACTURA f ON f.ID_COMPROBANTE = ce.ID_CBTE_COLOCACION AND EXTRACT(YEAR FROM f.FACT_FECHA) = EXTRACT(YEAR FROM ce.FECHA_EXTRACTO) 
WHERE cd.FECHA_CORTE = '2021-12-30' AND cd.ID_ESTADO IN (0,1,2)
)

SELECT 
	f.FACT_NUMERO AS NUMERO_FACTURA,
    f.FACT_FECHA AS FECHA_FACTURA,
	ce.ID_COLOCACION AS NUMERO_CREDITO,
	ce.CUOTA_EXTRACTO AS NUMERO_CUOTA,
	cc.ID_PERSONA AS DOCUMENTO_IDENTIDAD,
    ce.ID_CBTE_COLOCACION AS CONSECUTIVO,
	fi.FAIT_DETALLE AS CONCEPTO_FACTURA,
	fi.FAIT_TOTAL AS VALOR_CONCEPTO,
	f.FACT_ESTADO AS ESTADO_DIAN
FROM FACTURA f 
INNER JOIN FACTURA_ITEM fi ON fi.FACT_NUMERO = f.FACT_NUMERO 
INNER JOIN "col$extracto" ce ON ce.ID_CBTE_COLOCACION = f.ID_COMPROBANTE AND EXTRACT(YEAR FROM ce.FECHA_EXTRACTO) = EXTRACT(YEAR FROM f.FACT_FECHA)
INNER JOIN "col$colocacion" cc ON cc.ID_COLOCACION = ce.ID_COLOCACION;
