SELECT DISTINCT a.ID_PERSONA, a.NOMBRE, a.TELEFONO1, a.TELEFONO2, MAX(a.DIAS_MORA_MAXIMO) AS DIAS_MORA_MAXIMO FROM (
SELECT o.ID_COLOCACION, c.ID_PERSONA, p.NOMBRE || ' ' || p.PRIMER_APELLIDO || ' ' || p.SEGUNDO_APELLIDO AS NOMBRE, d.TELEFONO1, d.TELEFONO2, MAX(o.DIAS_MORA) AS DIAS_MORA_MAXIMO, c.ID_ESTADO_COLOCACION FROM ( 
SELECT ced.ID_COLOCACION, ced.FECHA_EXTRACTO, SUM(ced.DIAS_APLICADOS) AS DIAS_MORA
 FROM "col$extractodet" ced 
 WHERE ced.TASA_LIQUIDACION >= 48.5 AND ced.FECHA_EXTRACTO >= '2015-01-01'
 GROUP BY ced.ID_COLOCACION, ced.FECHA_EXTRACTO
 HAVING SUM(ced.DIAS_APLICADOS) <= 45) o
LEFT JOIN "col$colocacion" c ON c.ID_COLOCACION = o.ID_COLOCACION
LEFT JOIN "gen$persona" p ON p.ID_IDENTIFICACION  = c.ID_IDENTIFICACION AND p.ID_PERSONA = c.ID_PERSONA
LEFT JOIN "gen$direccion" d ON d.ID_IDENTIFICACION  = c.ID_IDENTIFICACION AND d.ID_PERSONA = c.ID_PERSONA AND d.ID_DIRECCION = 1
WHERE c.ID_ESTADO_COLOCACION IN (0,7)
GROUP BY o.ID_COLOCACION, c.ID_PERSONA, p.NOMBRE, p.PRIMER_APELLIDO, p.SEGUNDO_APELLIDO, c.ID_ESTADO_COLOCACION, d.TELEFONO1, d.TELEFONO2) a
GROUP BY a.ID_PERSONA, a.NOMBRE, a.TELEFONO1, a.TELEFONO2