GRANT ALL ON FACTURA TO CARTERA;
GRANT ALL ON FACTURA TO CAPTACIONES;
GRANT ALL ON FACTURA TO CREDITOS;

GRANT ALL ON FACTURA_ITEM TO CARTERA;
GRANT ALL ON FACTURA_ITEM TO CAPTACIONES;
GRANT ALL ON FACTURA_ITEM TO CREDITOS;

GRANT ALL ON FAC_AUTORIZACION TO CARTERA;
GRANT ALL ON FAC_AUTORIZACION TO CAPTACIONES;
GRANT ALL ON FAC_AUTORIZACION TO CREDITOS;

GRANT ALL ON FAC_FORMA_PAGO TO CARTERA;
GRANT ALL ON FAC_FORMA_PAGO TO CAPTACIONES;
GRANT ALL ON FAC_FORMA_PAGO TO CREDITOS;

GRANT ALL ON FAC_METODO_PAGO TO CARTERA;
GRANT ALL ON FAC_METODO_PAGO TO CAPTACIONES;
GRANT ALL ON FAC_METODO_PAGO TO CREDITOS;

GRANT ALL ON FAC_TIPO_CONTINGENCIA TO CARTERA;
GRANT ALL ON FAC_TIPO_CONTINGENCIA TO CAPTACIONES;
GRANT ALL ON FAC_TIPO_CONTINGENCIA TO CREDITOS;

GRANT ALL ON FAC_TIPO_IDENTIFICACION TO CARTERA;
GRANT ALL ON FAC_TIPO_IDENTIFICACION TO CAPTACIONES;
GRANT ALL ON FAC_TIPO_IDENTIFICACION TO CREDITOS;

GRANT ALL ON FAC_TIPO_OPERACION TO CARTERA;
GRANT ALL ON FAC_TIPO_OPERACION TO CAPTACIONES;
GRANT ALL ON FAC_TIPO_OPERACION TO CREDITOS;

GRANT ALL ON FAC_TIPO_PERSONA TO CARTERA;
GRANT ALL ON FAC_TIPO_PERSONA TO CAPTACIONES;
GRANT ALL ON FAC_TIPO_PERSONA TO CREDITOS;

GRANT ALL ON FAC_TIPO_REGIMEN TO CARTERA;
GRANT ALL ON FAC_TIPO_REGIMEN TO CAPTACIONES;
GRANT ALL ON FAC_TIPO_REGIMEN TO CREDITOS;